



services: # Описывает контейнеры, которые необходимо запустить
  smoke-api-test: #
    image: api:v1 # Указывает образ Docker, на основе которого будет создан контейнер.
    build: #  Содержит инструкции по сборке образа, если он несуществует локально.
      context: . # Директория, в которой находится Dockerfile
      dockerfile: Dockerfile # Имя Dockerfile
    volumes: # Позволяет монтировать директории из хост-системы в контейнер (аналог `-v`).
      - ./:/usr/workspace
    command: /bin/sh -c "STAGE=$$STAGE pytest -sv -o log_cli=true -n=$$THREADS -m=$$MARKER --alluredir=allure-results"#
    environment: # Определяет переменные окружения в контейнере.
      STAGE: ${STAGE}
      MARKER: ${MARKER:-smoke}
      THREADS: ${THREADS:-2}
    tty: true # Для цветного вывода логов

#  regression_api:
#    image: api:v1
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/usr/workspace
#    command: /bin/sh -c "STAGE=$$STAGE pytest -sv -o log_cli=true"
#    environment:
#      STAGE: ${STAGE}
#    tty: true

  report:
    image: api:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && allure generate allure-results --clean -o allure-report"
    working_dir: /usr/workspace