name: API Tests
run-name: Test ${{ github.event.inputs.ENV }} | ${{ github.event.inputs.MARKER }} marker | ${{ github.event.inputs.THREADS }} threads

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Choose environment"
        required: true
        type: environment

      MARKER:
        description: "Choose tests marker (smoke/regression)"
        required: true
        default: "smoke"
        type: choice
        options:
          - smoke
          - regression

      THREADS:
        description: "Parallel threads count"
        required: false
        type: choice
        default: "2"
        options:
          - "2"
          - "5"

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}  # ✅ Привязка джоба к выбранному environment

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Prepare Allure environment
        run: |
          mkdir -p allure-results
          echo "Branch=${{ github.ref_name }}" > allure-results/environment.properties
          echo "Commit=${{ github.sha }}" >> allure-results/environment.properties
          echo "Stage=${{ secrets.STAGE }}" >> allure-results/environment.properties
          echo "Marker=${{ inputs.MARKER }}" >> allure-results/environment.properties
          echo "Threads=${{ inputs.THREADS }}" >> allure-results/environment.properties

      - name: Run tests via docker-compose
        env:
          STAGE: ${{ secrets.STAGE }}
          MARKER: ${{ inputs.MARKER }}
          THREADS: ${{ inputs.THREADS }}
        run: |
          docker compose up smoke-api-test

      - name: Copy Allure history
        run: |
          mkdir -p allure-results/history
          if [ -d "./.github/gh-pages/history" ]; then
            cp -R ./.github/gh-pages/history/* allure-results/history/
          fi

      - name: Generate Allure-report
        run: |
          docker compose up report

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: false